### ISSUE TITLE
Unable to pull docker image for notary server from ghcr

### ISSUE THREAD

**Issue by th4s** [tlsnotary/tlsn#381]
Following these [instructions](https://github.com/tlsnotary/tlsn/tree/dev/notary-server#github) to obtain the docker image from github, I get an error:
```
docker pull ghcr.io/tlsnotary/tlsn/notary-server:latest
Error response from daemon: Head "https://ghcr.io/v2/tlsnotary/tlsn/notary-server/manifests/latest": denied
```

This should be repaired.

**Comment by heeckhau** [comment]
I assume this must be:
```
docker pull ghcr.io/tlsnotary/notary-server:latest
```

**Comment by yuroitaki** [comment]
Thanks for spotting this @th4s! This is mainly because I thought we will release a new docker image using tlsn repo after migration of notary-server into tlsn repo, which we decided not to, hence the README is outdated — for now we definitely should point the docker image url in README to the image released in the old notary-server repo. More info here: https://discord.com/channels/974410303255232542/1149188213043384410/1161945672099057685
