### ISSUE TITLE
Circuit IO type conversions

### ISSUE THREAD

**Issue by sinui0** [tlsnotary/tlsn#56]
Right now our mpc-circuits API requires the User to work with `Vec<bool>` values. This is very clunky, as in most cases a circuit input or output is going to be a native type, eg `u8, u16, u32, u64, u128`.

Let's update our `Input` and `Output` models to allow users to work with native types

For example:

```rust
pub enum ValueType {
  BoolVec,
  U8,
  U16,
  U32,
  ..
}

pub enum Value {
  BoolVec<Vec<bool>>,
  U8(u8),
  U16(u16),
  U32(u32),
  ..
}

pub struct Input {
  id: usize,
  type: ValueType,
  wires: Vec<usize>
}

pub struct InputValue {
  input: Input,
  value: Value
}

impl Circuit {
  pub fn evaluate(&self, inputs: &[InputValue]) -> Result<Vec<OutputValue>, Error> {
    // Maps input values to wires
    ..
  }
}
```

**Comment by th4s** [comment]
Is it possible to do it without `ValueType`?

```rust
pub enum Value {
  BoolVec<Vec<bool>>,
  U8(u8),
  U16(u16),
  U32(u32),
  ..
}

pub struct InputValue {
  id: usize
  wires: Vec<usize>
  value: Value
}

```

**Comment by th4s** [comment]
I am probably not deep enough into circuits. My understanding was, that you want a better encoding for the boolean input/output values of a circuit. Do you mean that we need the `ValueType` for a circuit instance without input values in order to indicate which input types we need to provide to the circuit as input values?

**Comment by th4s** [comment]
I see, then we probably need it, currently have no clever idea to do it without.
